version: '3.8'

services:
  translator:
    image: simple-translator:latest
    ports:
      - 3000:3000
    networks:
      - mynet

  docker-mysql:
    image: mysql:5.7
    container_name: docker-mysql1
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'translations'
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet

networks:
  mynet:

volumes:
   db-data:
